export const MODULES = [
  {
    id: 'home',
    title: 'Home',
    slug: 'home',
    tagline: 'The Lab — DS/ML/AI explainer.',
    phase: 0,
    unlocked: true,
    loader: () => import('./home/home.js'),
  },
  {
    id: 'lobby',
    title: 'The Lobby',
    slug: 'lobby',
    tagline: 'Draw points. Watch a line appear. No words needed.',
    phase: 0,
    unlocked: true,
    narrative: `Welcome, researcher.\n\nBefore we begin any formal training, I want you to try something simple.\n\nClick anywhere on the canvas to place a data point. Place a few more.\n\nWatch what happens. No equations yet. No theory.\n\nJust click.\n\n— Dr. Vector`,
    loader: () => import('./lobby/lobby.js'),
  },
  {
    id: 'data-shape',
    title: 'Shape of Data',
    slug: 'data-shape',
    tagline: 'Data has geometry. Learn to see it.',
    phase: 2,
    unlocked: false,
    narrative: `Every dataset has a shape. Before you model anything, you need to see what you're working with.\n\n— Dr. Vector`,
    loader: () => import('./data-shape/data-shape.js'),
  },
  {
    id: 'bias-variance',
    title: 'Bias/Variance Lab',
    slug: 'bias-variance',
    tagline: 'Too simple. Too complex. The knife edge between.',
    phase: 1,
    unlocked: true,
    narrative: `A model that's too simple can't capture the truth. Too complex, and it memorises noise.\n\nGenerate a noisy sine dataset. Set degree to 1 — the line can't follow the curve (underfitting).\n\nNow crank the degree to 12. The curve chases every point. Reveal the test set. Watch what happens.\n\nThe model learned the noise, not the pattern. That's overfitting.\n\n— Dr. Vector`,
    loader: () => import('./bias-variance/bias-variance.js'),
  },
  {
    id: 'gradient-descent',
    title: 'Gradient Descent Terrain',
    slug: 'gradient-descent',
    tagline: 'Learning is just hiking downhill — carefully.',
    phase: 1,
    unlocked: true,
    narrative: `Imagine you're blindfolded on a hilly landscape. Your goal: find the lowest valley.\n\nYou can only feel the slope beneath your feet. Each step, you move downhill. That slope is the gradient.\n\nTry SGD with a high learning rate — watch it bounce. Drop it low — watch it crawl. Then try Adam. It adapts the step size per direction and converges cleanly.\n\nThe green dot is the minimum. Your job: reach it.\n\n— Dr. Vector`,
    loader: () => import('./gradient-descent/gradient-descent.js'),
  },
  {
    id: 'decision-forest',
    title: 'Decision Forest',
    slug: 'decision-forest',
    tagline: 'One tree is brittle. A thousand trees are wise.',
    phase: 2,
    unlocked: false,
    narrative: `A single decision tree is just a game of twenty questions. It can be fooled.\n\nBut a thousand trees, each trained on a slightly different view of the data? That's a jury.\n\n— Dr. Vector`,
    loader: () => import('./decision-forest/decision-forest.js'),
  },
  {
    id: 'neural-architecture',
    title: 'Neural Architecture Hall',
    slug: 'neural-architecture',
    tagline: 'Neurons vote. Layers abstract. Mistakes teach.',
    phase: 1,
    unlocked: true,
    narrative: `Each neuron computes a weighted sum of its inputs, then passes it through an activation function — the "opinion filter."\n\nWithout that filter (linear mode), any deep network collapses to a single linear transformation. It cannot solve XOR — a problem no straight line can separate.\n\nSwitch to sigmoid. Pick an input. Run the forward pass. Watch activations propagate layer by layer.\n\nBlue edges carry positive weights. Red carry negative. Brightness shows activation strength.\n\n— Dr. Vector`,
    loader: () => import('./neural-architecture/neural-architecture.js'),
  },
  {
    id: 'convolution-engine',
    title: 'Convolution Engine',
    slug: 'convolution-engine',
    tagline: 'A sliding spotlight that learns what to look for.',
    phase: 2,
    unlocked: false,
    narrative: `A convolution is just a small pattern template sliding across an image, asking: "do you look like me?"\n\n— Dr. Vector`,
    loader: () => import('./convolution-engine/convolution-engine.js'),
  },
  {
    id: 'attention-chamber',
    title: 'Attention Chamber',
    slug: 'attention-chamber',
    tagline: 'Every word consults every other word.',
    phase: 2,
    unlocked: false,
    narrative: `In a room full of people, attention is about who is listening to whom.\n\nTransformers do the same thing — but with words.\n\n— Dr. Vector`,
    loader: () => import('./attention-chamber/attention-chamber.js'),
  },
  {
    id: 'embedding-universe',
    title: 'Embedding Universe',
    slug: 'embedding-universe',
    tagline: 'Meaning has coordinates.',
    phase: 2,
    unlocked: false,
    narrative: `Words aren't symbols. In a learned embedding space, they're locations — and similar meanings live close together.\n\n— Dr. Vector`,
    loader: () => import('./embedding-universe/embedding-universe.js'),
  },
  {
    id: 'evaluation-observatory',
    title: 'Evaluation Observatory',
    slug: 'evaluation-observatory',
    tagline: 'Accuracy lies. Learn what to actually measure.',
    phase: 2,
    unlocked: false,
    narrative: `A disease detector that labels everyone "healthy" has 99% accuracy — if 1% of people are sick.\n\nAccuracy lies. The question is: what are the consequences of being wrong?\n\n— Dr. Vector`,
    loader: () => import('./evaluation-observatory/evaluation-observatory.js'),
  },
  {
    id: 'generative-studio',
    title: 'Generative Studio',
    slug: 'generative-studio',
    tagline: 'The forger and the detective — training together.',
    phase: 3,
    unlocked: false,
    narrative: `One network tries to fake. Another tries to detect fakes. They train each other into competence.\n\n— Dr. Vector`,
    loader: () => import('./generative-studio/generative-studio.js'),
  },
];
